# -*- coding: utf-8 -*-
"""fah_converter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14P4o8dGXBKAquoi6-CJeihIZK4ODXcyK
"""

def covert_c_to_f(celcius_value):
    return celcius_value * 9.0 / 5 + 32